apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    env: dev
spec:
  template:
    metadata:
      labels:
         env: dev

    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      env: dev
